### ISSUE TITLE
Plugin not working !

### ISSUE THREAD

**Issue by lululock71** [ElCholoGamer/userlogin#43]
Hi,
I've set up the latest version of userlogin with the latest version of PaperMC (1.18.2).

Even after checking the config files, I noticed all connected players can move, destroy blocks and type commands when they are not registered/logged in in userlogin.

I don't know what causes the issue, there's no error in server logs.

This issue is very annoying and defeats the purpose of the plugin itself...

**Comment by Grazen0** [comment]
This isn't a bug, you have to enable those restrictions in the config.yml file.

**Comment by organizatsiya** [comment]
```
restrictions:
  chat: true
  commands: true
  blockBreaking: true
  blockPlacing: true
  itemDrop: true # Can cause items to disappear if dropped from the inventory UI. Enable inventoryClick to prevent this
  itemPickup: true # 1.12+ only
  inventoryClick: true
  damage:
    attack: true
    receive: true
  movement:
    enabled: true
    warnFrequency: 10 # Message players every few ticks when they move. (-1 to disable)

```
